### ISSUE TITLE
Update Zarf Main Read me 

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf-docs#18]
Replace main read me on Zarf with new overview information

Needed because it is being pulled by other sites on the web - like this one

https://www.opensourceagenda.com/projects/zarf

**Comment by Racer159** [comment]
@Madeline-UX this should be taken care of with the closure of https://github.com/defenseunicorns/zarf/pull/672 are you able to confirm?  Anything else needed for this ticket?

**Comment by Madeline-UX** [comment]
@Racer159 Looks good. Will close issue.
