### ISSUE TITLE
Add guided walkthroughs to the docs

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/zarf-docs#23]
Simple guides that people can follow to get more familiar with Zarf and its features. These should include covering basic introductionary walkthroughs of Zarf and semi-detailed instructions on how to use the example packages we provide in the repo.

These can be built out to be more extensive in the future.

**Comment by Madeline-UX** [comment]
@YrrepNoj  Can this issue be closed for now? Or is there a list of walkthroughs that we can add to the story to be completed?

**Comment by Madeline-UX** [comment]
@YrrepNoj closing for now since there are a good first group of walk throughs. Future walk throughs can be new issues.
