### ISSUE TITLE
Create GitHub Workflow to auto-create PRs to update 'zarf-repo' submodule  

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/zarf-docs#41]
The documentation files for this webpage is now brought in as a `git submodule` of the main [zarf repo](https://github.com/defenseunicorns/zarf). Whenever there are new changes to the `docs/` directory in the main repository is updated we need to update the submodule to point to the most recent commit in `master` on that repo. 

We should create a workflow that automatically creates that PR.

**Comment by Madeline-UX** [comment]
@jeff-mccoy @razzle thoughts?
