### ISSUE TITLE
Issues with Zarf Package Schema page

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf-docs#43]
Looking through the Zarf Package Schema page, I'm seeing a couple of issues:

- The items on the right are all dead links. They don't move me around in the page like they intend to.
<img width="344" alt="image" src="https://user-images.githubusercontent.com/16000938/180014616-7a877f3d-32c8-4d14-a83f-62ac8debaf09.png">

- Some of the entries don't have descriptions
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/16000938/180014807-ef306c5f-e6f5-4f18-aabc-21a014d0fd46.png">

**Comment by Madeline-UX** [comment]
@RothAndrew This was created from a JSON file and I think the broken links are due to missing the proper headers that would create the links. 

@mike-winberry do you have any insights on this?

**Comment by jeff-mccoy** [comment]
For description those will be resolved when we push the docs site update after this next release.  We don't have doc versioning yet so we have to wait for a release to update docs 😢. @Racer159 I think did the sidenav links before for this.

**Comment by Racer159** [comment]
Those sidenavs are autogenerated from the `<hx>` tags on the page.  They will work if you expand the `<details>` first, but obviously that is not ideal.  Likely the best option might be to just not use <hx> tags to make the sidebar go away.  This is actually currently being debated by web standards organizations with Mozilla currently being in favor of allowing for autoexpansion of elements with hidden=until-found https://github.com/mozilla/standards-positions/issues/612
