### ISSUE TITLE
Documentation search provider

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf-docs#48]
It would be nice to use the Algolia DocuSearch provider for search (https://docusaurus.io/docs/search#using-algolia-docsearch) as it is officially supported by the project and free for Open Source projects, though would require registration and obtaining an API key.

**Comment by Racer159** [comment]
@YrrepNoj and @jeff-mccoy thoughts?

**Comment by Madeline-UX** [comment]
@mike-winberry you spent a lot of time trying to customize docusaurus - any thoughts on this?

**Comment by mike-winberry** [comment]
It makes the search useless in air gap. If they ever wanted to deploy the docs within airgap.

**Comment by jeff-mccoy** [comment]
I definitely think we will want the docs site in airgap with the ui eventually, something to keep in mind.

**Comment by Madeline-UX** [comment]
I agree with the desired outcome of wanting to deploy docs in airgap at some point - ideally with search functionality

**Comment by mike-winberry** [comment]
Are we opposed to forking the implementation? Looks like many of the local searches are not up to date and this is the most flushed out, shouldn't be difficult to maintain and better than re-inventing the wheel. But open to other suggestions and going to keep playing.

**Comment by RothAndrew** [comment]
Are there other search implementations that can be used when disconnected? A pattern that I've seen before is to use the best search functionality if available, with a fallback to a less powerful version if the best one isn't available.

Obviously we would need to weigh the need to maintain more than one search implementation vs picking one that works in air gap, vs forking as you mentioned

**Comment by Madeline-UX** [comment]
@jeff-mccoy  Here is a comparison of the current search functionality and the updated search bar #53 

I am concerned about the loss of functionality with the new search component. The current one is much more user friendly, robust, and easier to navigate and read (symbols, full page names, routes, and see full results page) 

I wonder if @RothAndrew idea of using the current option when connected then having the new option available as a fall back when deployed disconnected? 

## Current search component ##

https://user-images.githubusercontent.com/92826525/187478720-61fb7a33-81ad-49a6-a8fd-026c48e7476c.mov

## Proposed updated search component ##

https://user-images.githubusercontent.com/92826525/187478850-67e46c38-887c-46c2-8df2-91b2c3097587.mov

**Comment by Madeline-UX** [comment]
Closing for now. Will reopen if we decide there is value in replacing current search bar
