### ISSUE TITLE
Edit this page link is broken

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf-docs#50]
Currently: 

When a user clicks on the "edit this page" link at the bottom of any docs page it redirects to 404 page on github. 

Update:

Need to update link to Zarf github - possibly specifically to the page where Zarf docs code is located.

**Comment by Madeline-UX** [comment]
@YrrepNoj thoughts on this?

**Comment by YrrepNoj** [comment]
@Racer159 looks like this broke when we started doing the submodule.. whoops

Is this something we can still do if we're brining in all .md files instead of just the docs repo with your PR #47 ?

**Comment by Racer159** [comment]
This is fixed in #47
