### ISSUE TITLE
Underscores in Zarf CLI Reference Docs

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/zarf-docs#58]
The docs on zarf.dev show the CLI commands with underscores between them. Would be great if these underscores were removed so it's not as confusing when first viewing the CLI reference
![Screen Shot 2022-11-09 at 7 44 40 AM](https://user-images.githubusercontent.com/42304551/200846229-6f346a68-0693-4220-a87c-e2c1937d31de.png)

**Comment by jeff-mccoy** [comment]
I do think this is mitigated by the fact that both the actual cli and the primary docs contents show without a space, e.g. https://docs.zarf.dev/docs/user-guide/the-zarf-cli/cli-commands/zarf_package_create#synopsis.

![image](https://user-images.githubusercontent.com/882485/200847217-c4013de8-ea69-4228-87eb-dcf40910a81e.png)

**Comment by UncleGedd** [comment]
Agreed its nitpicky 😆. I'm happy to look into it though if the Zarf team has other priorities
