### ISSUE TITLE
The "GitHub" link on the docs site links to the wrong repo (IMO)

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf-docs#6]
It's confusing that the "GitHub" link on the docs site links to the Zarf repo, instead of this one.

Typically, you'll see a button on a docs site that says "Edit this page on GitHub", or something to that effect.

**Comment by Madeline-UX** [comment]
I agree that it makes sense for the github link to link to the zarf repo since the zarf repo is what the user will most likely be looking to access from the docs 

And as stated above they have that option to access the docs repo at the bottom of the page.
