### ISSUE TITLE
Update Contributor Guide

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf-docs#7]
The Contributor guide needs the steps that talk about running `/test all` removed, since we don't do that anymore.

Side-note: What is the plan for de-duplicating the contributor guides between the docs site and the Zarf repo?

**Comment by Racer159** [comment]
This should be resolved when https://github.com/defenseunicorns/zarf-docs/pull/47 is merged in.  The CONTIRUBITING.md file was updated a while ago, but that PR DRYs the two copies out.
